---
# Ansible Galaxy requirements file
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: community.general
    version: ">=7.0.0"
  
  - name: ansible.posix
    version: ">=1.5.0"

roles:
  # Example: AUR helper for Arch Linux
  # - src: kewlfft.aur
  #   version: master