all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: "{{ lookup('env', 'USER') }}"
  children:
    workstations:
      hosts:
        localhost:
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"