---
# Package definitions for different operating systems
packages:
  base:
    common:
      - curl
      - wget
      - aria2
      - git
      - vim
      - tmux
      - htop
      - tree
      - unzip
      - jq
      - ncdu
      - rsync
      - openssh-client
      - mosh
      - iotop
      - nload
      - nethogs
      - pigz
      - pwgen
    ubuntu:
      - build-essential
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - net-tools
      - dnsutils
      - firefox
      - chromium-browser
      - gedit
      - eog
      - libheif1
      - vlc
      - flameshot
    debian:
      - build-essential
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - net-tools
      - dnsutils
      - gedit
      - eog
      - libheif1
      - vlc
      - flameshot
    fedora:
      - gcc
      - gcc-c++
      - make
      - kernel-devel
      - dnf-plugins-core
      - util-linux-user
      - bind-utils
      - gedit
      - eog
      - libheif
      - vlc
      - flameshot
    arch:
      - base-devel
      - net-tools
      - bind
      - firefox
      - chromium
      - discord
      - gnome-extra
      - gedit
      - eog
      - libheif
      - vlc
      - vlc-plugin-all
      - cheese
      - gnu-netcat
      - flameshot
    darwin:
      - coreutils
      - gnu-tar
      - gnu-sed
      - gawk
      - gnutls
      - gnu-indent
      - gnu-getopt
      - findutils
      - bash
      - grep
      - wget
      - curl

  development:
    common:
      - neovim
      - ripgrep
      - fzf
      - httpie
      - direnv
      - redis
      - mariadb
      - memcached
      - docker
      - docker-compose
      - python-pipenv
      - pyenv
      - lazydocker
    ubuntu:
      - python3-pip
      - python3-venv
      - python3-dev
      - nodejs
      - npm
      - golang
      - rustc
      - cargo
    debian:
      - python3-pip
      - python3-venv
      - python3-dev
      - nodejs
      - npm
      - golang
      - rustc
      - cargo
    fedora:
      - python3-pip
      - python3-devel
      - nodejs
      - npm
      - golang
      - rust
      - cargo
    arch:
      - python-pip
      - nodejs
      - npm
      - pnpm
      - aur/fnm
      - go
      - rust
      - uv
      - extra/python-poetry
      - postgresql
    darwin:
      - python@3.11
      - node
      - go
      - rust
      - fd
      - bat
      - exa
      - jq
      - tree
      - htop
      - tmux
      - git

  extras:
    common:
      - tig
      - tldr
      - ncdu
      - duf
      - dust
      - procs
      - bottom
      - zoxide
      - syncthing
      - syncthing-gtk
      - transmission-gtk
      - keepassxc
      - google-chrome
      - vorta
      - pinta
    ubuntu:
      - silversearcher-ag
    debian:
      - silversearcher-ag
    fedora:
      - the_silver_searcher
    arch:
      - the_silver_searcher
      - pycharm-professional
      - webstorm
      - webstorm-jre
      - signal-desktop
      - visual-studio-code-bin
      - gitkraken
      - gitkraken-cli
      - insomnia-bin
      - libreoffice-fresh
      - aur/repomix
      - kuro
      - aur/ventoy-bin
      - aur/makemkv
    darwin:
      - the_silver_searcher

# Package name mappings for cross-platform compatibility
package_map:
  fd-find:
    default: fd-find
    arch: fd
    fedora: fd-find
    darwin: fd
  bat:
    default: bat
    ubuntu: bat
    debian: bat
    arch: bat
    fedora: bat
    darwin: bat
  exa:
    default: exa
    ubuntu: exa
    debian: exa
    arch: exa
    fedora: exa
    darwin: exa
  openssh-client:
    default: openssh-client
    archlinux: openssh
    darwin: openssh
  openssh-server:
    default: openssh-server
    archlinux: openssh
    darwin: openssh
  docker:
    default: docker
    ubuntu: docker-ce
    debian: docker-ce
    archlinux: docker
    fedora: docker
    darwin: docker
  docker-compose:
    default: docker-compose
    ubuntu: docker-compose-plugin
    debian: docker-compose-plugin
    archlinux: docker-compose
    fedora: docker-compose
    darwin: docker-compose
  python-pipenv:
    default: python-pipenv
    ubuntu: pipenv
    debian: pipenv
    archlinux: python-pipenv
    fedora: pipenv
    darwin: pipenv
  pyenv:
    default: pyenv
    ubuntu: pyenv
    debian: pyenv
    archlinux: pyenv
    fedora: pyenv
    darwin: pyenv