---
- name: Install Docker prerequisites (Debian/Ubuntu)
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker GPG key (Debian/Ubuntu)
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker repository (Debian/Ubuntu)
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  when: ansible_os_family == 'Debian'

- name: Install Docker (Debian/Ubuntu)
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Docker (Fedora)
  dnf:
    name:
      - docker
      - docker-compose
    state: present
  when: ansible_distribution == 'Fedora'

- name: Install Docker (Arch)
  pacman:
    name:
      - docker
      - docker-compose
    state: present
  when: ansible_os_family == 'Archlinux'

- name: Ensure docker group exists (Arch)
  group:
    name: docker
    state: present
  become: yes
  when: ansible_os_family == 'Archlinux'

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
  become: yes
  notify: restart docker

- name: Display docker group membership note
  debug:
    msg: "User {{ user }} has been added to the docker group. You may need to log out and back in for this to take effect."
  when: ansible_os_family == 'Archlinux'

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Install docker-compose standalone (if not installed)
  get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  when: ansible_os_family == 'Debian'