---
- name: Install VS Code (Debian/Ubuntu)
  block:
    - name: Add Microsoft GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add VS Code repository
      apt_repository:
        repo: "deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main"
        state: present
        filename: vscode

    - name: Install VS Code
      apt:
        name: code
        state: present
        update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install VS Code (Fedora)
  block:
    - name: Import Microsoft GPG key
      rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add VS Code repository
      yum_repository:
        name: vscode
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: yes
        gpgcheck: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc

    - name: Install VS Code
      dnf:
        name: code
        state: present
  when: ansible_os_family == 'RedHat'

- name: Install VS Code (Arch)
  aur:
    name: visual-studio-code-bin
    state: present
  become: false
  when: ansible_os_family == 'Archlinux'

- name: Install VS Code (macOS)
  homebrew_cask:
    name: visual-studio-code
    state: present
  become: false
  when: ansible_os_family == 'Darwin'