---
- name: Check if yay is installed
  command: which yay
  register: yay_check
  changed_when: false
  failed_when: false

- name: Install yay from AUR
  block:
    - name: Install dependencies for building yay
      pacman:
        name:
          - base-devel
          - git
        state: present

    - name: Clone yay repository
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: /tmp/yay
        version: master
      become: false

    - name: Build and install yay
      shell: |
        cd /tmp/yay
        makepkg -si --noconfirm
      become: false
      args:
        creates: /usr/bin/yay

    - name: Clean up yay build directory
      file:
        path: /tmp/yay
        state: absent
  when: yay_check.rc != 0